### ISSUE TITLE
Meta Plan for December

### ISSUE THREAD

**Issue by octref** [underlay/underlay.org#106]
Let's ship a preview version in December:

- Users by invite only
- Hand select dataset collections and we publish them manually
- Gather feedback for further iterations

### Tasks

- [x] Drop exports tab @octref
- [x] Combine schema/data into one Data tab (mockups) @isTravis @octref
- [x] Make the download button on CollectionLanding to download JSON data with metadata (simple mapping) @octref
- [x] Remove CSV download for now @octref
- [x] CLI yaml spec @isTravis
- [ ] CLI to download types @octref

**Comment by octref** [comment]
Done and closed.
