### ISSUE TITLE
MVP Meta Plan

### ISSUE THREAD

**Issue by octref** [underlay/underlay.org#87]
Home page:

- [x] Query -> `/search?q=query` with all matching results displayed 
- [x] Copyedit the text
- [x] Leave Discover page for later

Collection page:

- [x] Put the `description` field somewhere

Profile page:

For user profile:
- [x] Remove the Communities page pointing to `/profile/communities`
- [x] Collection review block (show version number, show last version date)
- [x] Settings page: edit slug, delete account, an about field that is displayed just above the `communities` on `/profile` page
- [x] When no collections - show something or a button to create new collection
- [x] Empty state for no communities joined
- [x] Only show `settings` when I’m the user

For community profile:

- [x] Implement a minimal `/community/members` page
  - [x] Add/remove member (only allow admin to do that)
  - [ ] Set member permissions (admin/member)
- [x] Empty `about` field - hide `about`
- [x] Empty state for no collections created
- [x] Implement a minimal `/community/settings` page (name, slug, delete, about)
- [x] Only show `settings` when I’m an admin for a community

For collection overview page:

- [x] Timeline for all events
- [x] On the right side, when data has been updated, show version, last published, size, collaborators and a Download Section (size is impossible – each export x version makes the size different. collaborators is pending on changes to associate `collaborators` with the `Collection` model)
  - [x] Download Section: ‘Create export’ or ‘View N exports’
- [x] Remove the star next to `namespace/collection` on the top

For collection schema page:

- [x] Improve the design ❓ 

For collection data page:

- [x] Helper text for the 3 Upload Behaviors (@isTravis)
- [x] Improve the relationship viewer (currently it only displays the UUIDs of the related entities). Only show 2-3 properties from each node and reveal the full Node detail in a hover

For collection discussions page:

- [x] Implement a minimal version where each discussion can be associated with a specific entity
  - [x] Data tab: add a button in each entity block that creates a new discussion pertaining to it

For collection exports page:

- [x] Show size in the table
- [x] Upon clicking the `mapping`, show a popup that describes the mapping
- [x] Remove the star
- [x] Clean up the Exports listing table
- [x] Support CSV exports
- [x] Show a preview of JSON/CSV export shape before exporting

For collection settings page:

- [x] Implement a basic collection settings page
  - Show `name`
  - Allow renaming
  - Editing the `description` field
  - Editing privacy
  - Add collaborators – allows uploading data & publish a new version
  - Owner only: delete collection
  - Members sub-tab: add/remove collaborators functionality for owner, display members for non-owner
